apiVersion: apps/v1
kind: Deployment
metadata:
  name: remove-watermark-api
  labels:
    app: remove-watermark-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remove-watermark-api
  template:
    metadata:
      labels:
        app: remove-watermark-api
    spec:
      containers:
      - name: remove-watermark-api
        image: beancookie/remove-watermark-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8100
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8100
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8100
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: remove-watermark-api
spec:
  selector:
    app: remove-watermark-api
  ports:
    - protocol: TCP
      port: 8100      
      targetPort: 8100  
  type: ClusterIP
