name: Releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.7'
      - run: go test -v -cover
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
