name: Releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.7'
      - run: go test -v -cover
  build:
    name: Run build
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 11.22.7
          binary_name: "parse-vide" 
          extra_files: README.md
