name: Releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.7'
      - run: go test -v -cover
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.22.7.linux-amd64.tar.gz"
        binary_name: "parse-video"
        extra_files: LICENSE README.md
